### ISSUE TITLE
Illegal opcodes

### ISSUE THREAD

**Issue by 42Bastian** [LLeny/VkHandybug#20]
The 65c02 has no illegal opcodes. Opcodes not mapped act as NOP. With different number of bytes and cycles.

**Comment by LLeny** [comment]
Right, the idea was to provide a way to optionally break the emulation when one of those was hit, I am assuming that in a majority of cases this is unwanted and the user may want to track it down. Should I rename it ? Undocumented? Undefined?

**Comment by 42Bastian** [comment]
I'd go for "Undocumented" (as undefined is not correct) and not make it default break.
Rather add an option "Lynx I" and "Lynx II" as for example the "BBRx" and "BBSx" instruction are really illegal on Lynx I.
