### ISSUE TITLE
Crash with nostalgia

### ISSUE THREAD

**Issue by 42Bastian** [LLeny/VkHandybug#28]
0.6.4 crashes after a few seconds with nostalgia:
https://github.com/42Bastian/lynx_hacking/blob/master/nostalgia/nostalgia.lnx

**Comment by LLeny** [comment]
I couldn't have it to crash after a minute with nostalgia only, but I got it to crash with nostalgia and hovering the mouse on the disassembly. Could you have faced that issue ?
Does 8cdac7b fix it for you ?

**Comment by 42Bastian** [comment]
Now it works with the same .exe !? No idea why.
